name: Deploy to CDN

on:
  push:
    branches: 
      - deploy
  workflow_dispatch:

jobs:
  upload-assets:
    name: Upload Assets
    runs-on: ubuntu-latest
    env:
      build: ${{ !contains(github.event.head_commit.message, 'Scheduled stats update') }}
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Setup - gcloud / gsutil
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCS_SA_KEY }}
        project_id: ${{ secrets.GCS_PROJECT_ID }}
        export_default_credentials: true
    - name: Upload
      if: env.build
      run: |-
        gsutil -m rsync -r -d dist gs://$GCS_BUCKET
      env:
        GCS_BUCKET: ${{ secrets.GCS_BUCKET }}
    - name: Upload only list.json
      if: ${{ !env.build }}
      run: |-
        gsutil dist/list.json gs://$GCS_BUCKET/dist/list.json
      env:
        GCS_BUCKET: ${{ secrets.GCS_BUCKET }}
        
